In [1]:
# cek library kita
from __future__ import print_function

import IPython
print('IPython:', IPython.__version__)

import numpy
print('numpy:', numpy.__version__)

import pandas
print('pandas:', pandas.__version__)

import sklearn
print('scikit-learn:', sklearn.__version__)

IPython: 7.34.0
numpy: 1.25.2
pandas: 1.5.3
scikit-learn: 1.2.2


In [2]:
# load data dari database/dataset iris
from sklearn.datasets import load_iris

iris = load_iris()

In [3]:
# tipe data numpy
X, y = iris.data, iris.target
type(X)

numpy.ndarray

In [4]:
#tampilkan datanya
print(X[:5])
print(y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [5]:
# data pandas
import pandas as pd

df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target

df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [6]:
#proses cleaning di skip
#preprocesing hanya menggunakan data transform(scaling)
#proses data transform kita jadikan dengan modelling menjadi 1 pipeline


In [12]:
# buat pipeline untuk data numpy
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC

model_numpy = make_pipeline(StandardScaler(), LinearSVC())

In [15]:
# lakukan hal yang sama untuk data pandas
model_pandas = make_pipeline(StandardScaler(), LinearSVC())

In [13]:
# data numpy
# split data training-testing
import pickle
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

#split data numpy
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=46)
#split data pandas
df_train, df_test = train_test_split(df, test_size=0.2, random_state=46)


In [14]:
# train model data numpy
model_numpy.fit(X_train, y_train)

# evaluasi model
y_pred = model_numpy.predict(X_test)
print(classification_report(y_test, y_pred))

# simpan model
with open("model_numpy.pkl", "wb") as model_file:
    pickle.dump(model_numpy, model_file)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.88      0.78      0.82         9
           2       0.80      0.89      0.84         9

    accuracy                           0.90        30
   macro avg       0.89      0.89      0.89        30
weighted avg       0.90      0.90      0.90        30



In [16]:
# train model
model_pandas.fit(df_train.drop('target', axis=1), df_train['target'])

# evaluasi model
y_pred = model_pandas.predict(df_test.drop('target', axis=1))
print(classification_report(df_test['target'], y_pred))

# simpan model
with open("model_pandas.pkl", "wb") as model_file:
    pickle.dump(model_pandas, model_file)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.88      0.78      0.82         9
           2       0.80      0.89      0.84         9

    accuracy                           0.90        30
   macro avg       0.89      0.89      0.89        30
weighted avg       0.90      0.90      0.90        30



In [17]:
# inference model data numpy
new_data = [1, 2, 3, 4]

model_numpy.predict([new_data])

array([2])

In [21]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
#prediksi data baru, menghasilkan output: virginica

In [18]:
# inference model data pandas
new_data = [1, 2, 3, 4]
new_data = pd.DataFrame([new_data], columns=iris.feature_names)

model_pandas.predict(new_data)

array([2])

In [19]:
# load model
with open("model_pandas.pkl", "rb") as model_file:
    model = pickle.load(model_file)

In [20]:
# inference model
new_data = [1, 2, 3, 4]
new_data = pd.DataFrame([new_data], columns=iris.feature_names)

model.predict(new_data)

array([2])

In [22]:
new_data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  1                 2                  3                 4